---
- name: precheck system files
  command: |
    rm /etc/apt/sources.list.d/kubernetes.list
    rm /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  ignore_errors: yes

- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
    cache_valid_time: 3600
  loop: "{{ packages }}"

- name: enable docker service
  systemd:
    name: docker
    enabled: yes

- name: disable all swap partitions
  command:
    cmd: swapoff --all

- name: comment out swap entry
  command:
    cmd: sudo sed -i '/ swap / s/^/#/' /etc/fstab